<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
    <head>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Standard Error from JUnitTclTest</title>
    </head>
    <body>
        <pre>java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: Unknown inputs remain. Possible causality loop:
L_model_1893289564i

  in .CannotAnalysisWithPreemption.model_1893289564_region_1 and .CannotAnalysisWithPreemption.model_1893289564_region_1.L_model_1893289564i
	at ptolemy.actor.sched.FixedPointDirector.postfire(FixedPointDirector.java:515)
	at ptolemy.domains.sr.kernel.SRDirector.postfire(SRDirector.java:417)
	at ptolemy.actor.CompositeActor.postfire(CompositeActor.java:1668)
	at ptolemy.actor.Manager.iterate(Manager.java:852)
	at ptolemy.actor.Manager.execute(Manager.java:369)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ptolemy.util.test.junit.AutoKnownFailedTests.RunModel(AutoKnownFailedTests.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
Caused by: ptolemy.kernel.util.IllegalActionException: Unknown inputs remain. Possible causality loop:
L_model_1893289564i

  in .CannotAnalysisWithPreemption.model_1893289564_region_1 and .CannotAnalysisWithPreemption.model_1893289564_region_1.L_model_1893289564i
	at ptolemy.actor.sched.FixedPointDirector.postfire(FixedPointDirector.java:515)
	at ptolemy.domains.sr.kernel.SRDirector.postfire(SRDirector.java:417)
	at ptolemy.actor.CompositeActor.postfire(CompositeActor.java:1668)
	at ptolemy.actor.Manager.iterate(Manager.java:852)
	at ptolemy.actor.Manager.execute(Manager.java:369)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
</pre>
    </body>
</html>
