<?xml version="1.0" standalone="yes"?>
<!DOCTYPE doc PUBLIC "-//UC Berkeley//DTD DocML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/DocML_1.dtd">
<doc name="CatchExceptionAttribute" class="ptolemy.actor.lib.CatchExceptionAttribute">
  <description>
This attribute catches exceptions and attempts to handle them with the&#10; specified policy.  If the exception cannot be handled, the attribute&#10; indicates this to the Manager.  Status messages may be logged to a file.  </description>
  <author>Edward A. Lee, Elizabeth Latronico</author>
  <version>$Id$</version>
  <since>Ptolemy II 10.0</since>
  <Pt.ProposedRating>Red (beth)</Pt.ProposedRating>
  <Pt.AcceptedRating>Red (beth)</Pt.AcceptedRating>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="exceptionMessage">The exception message from the caught exception.</property>
    <!--ptolemy.data.expr.FileParameter-->
    <property name="logFileName">The file, if any, to log messages to.</property>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="policy">The error handling policy to apply if an exception occurs.&#10;&#10; One of:  Continue, Throw, Restart, Quit</property>
    <!--ptolemy.data.expr.StringParameter-->
    <property name="statusMessage">The latest action, if any, taken by the CatchExceptionAttribute.&#10;  For example, a notification that the model has restarted.&#10;  It offers a way to provide feedback to the user.</property>
</doc>
