<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
    <head>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Unit Test Results: All Errors</title>
        <link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
    </head>
    <body onload="open('allclasses-frame.html','classListFrame')">
        <h1>Unit Test Results.</h1>
        <table width="100%">
            <tr>
                <td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
            </tr>
        </table>
        <hr size="1">
        <h2>All Errors</h2>
        <table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
            <tr valign="top">
                <th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
            </tr>
            <tr valign="top" class="Error">
                <td><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackNumber.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html#[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackNumber.xml (RunModel)">[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackNumber.xml (RunModel)</a></td><td>Error</td><td>N/A
                    <br>
                    <br>
                    <code>java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:193)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the react function: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                          in .SerialLoopbackNumber.TrainableTest
                        <br>
                        Because:
                        <br>
                        Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2306)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1138)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1949)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)
                        <br>
                        	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)
                        <br>
                        	at ptolemy.actor.Manager.iterate(Manager.java:851)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:369)
                        <br>
                        	at ptolemy.actor.Manager.run(Manager.java:1263)
                        <br>
                        	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
                        <br>
                        Caused by: javax.script.ScriptException: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:399)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:206)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2281)
                        <br>
                        Caused by: /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1731:24 Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "1" is not within "1e-9" of the expected value "0"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:135)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:101)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:105)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:109)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:128)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$45691$76238A$require.L:1#react#invokeSpecificHandler(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1736)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$45690$75884A$require$cu1$restOf.L:1#react(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
                        <br>
                    </code></td><td>41.386</td>
            </tr>
            <tr valign="top" class="Error">
                <td><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackShort.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html#[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackShort.xml (RunModel)">[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackShort.xml (RunModel)</a></td><td>Error</td><td>N/A
                    <br>
                    <br>
                    <code>java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:193)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the react function: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                          in .SerialLoopbackShort.TrainableTest
                        <br>
                        Because:
                        <br>
                        Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2306)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1138)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1949)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)
                        <br>
                        	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)
                        <br>
                        	at ptolemy.actor.Manager.iterate(Manager.java:851)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:369)
                        <br>
                        	at ptolemy.actor.Manager.run(Manager.java:1263)
                        <br>
                        	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
                        <br>
                        Caused by: javax.script.ScriptException: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:399)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:206)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2281)
                        <br>
                        Caused by: /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1731:24 Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "32767" is not within "1e-9" of the expected value "32766"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:135)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:101)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:105)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:109)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:128)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$55476$76238A$require.L:1#react#invokeSpecificHandler(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1736)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$55475$75884A$require$cu1$restOf.L:1#react(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
                        <br>
                    </code></td><td>41.822</td>
            </tr>
            <tr valign="top" class="Error">
                <td><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackUnsignedByte.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/serial/test/junit/63_JUnitTclTest.html#[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackUnsignedByte.xml (RunModel)">[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/serial/test/auto/SerialLoopbackUnsignedByte.xml (RunModel)</a></td><td>Error</td><td>N/A
                    <br>
                    <br>
                    <code>java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:193)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the react function: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                          in .SerialLoopbackUnsignedByte.TrainableTest
                        <br>
                        Because:
                        <br>
                        Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2306)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1138)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1949)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)
                        <br>
                        	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)
                        <br>
                        	at ptolemy.actor.Manager.iterate(Manager.java:851)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:369)
                        <br>
                        	at ptolemy.actor.Manager.run(Manager.java:1263)
                        <br>
                        	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
                        <br>
                        Caused by: javax.script.ScriptException: Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764) in /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt; at line number 1731 at column number 24
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:399)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:206)
                        <br>
                        	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2281)
                        <br>
                        Caused by: /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1731:24 Error: commonHost.js, react(), invoking a specific handler for "input": Exception occurred in input handler for accessor TrainableTest, which has now has been removed.  Exception was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254" Stacktrace was: Error: TrainableTest: After seeing 0 tokens, the input "255" is not within "1e-9" of the expected value "254"
                        <br>
                        	at &lt;anonymous&gt; (&lt;function&gt;:267)
                        <br>
                        	at invokeSpecificHandler (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1719)
                        <br>
                        	at react (/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:135)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:101)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:105)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:109)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:128)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$76638$76238A$require.L:1#react#invokeSpecificHandler(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1736)
                        <br>
                        	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$76637$75884A$require$cu1$restOf.L:1#react(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#409:30&lt;eval&gt;:1764)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
                        <br>
                        	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
                        <br>
                    </code></td><td>41.109</td>
            </tr>
            <tr valign="top" class="Error">
                <td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/65_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message1.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/65_JUnitTclTest.html#[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message1.xml (RunModel)">[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message1.xml (RunModel)</a></td><td>Error</td><td>N/A
                    <br>
                    <br>
                    <code>java.lang.reflect.InvocationTargetException
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:193)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        <br>
                        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
                        <br>
                        ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.
                        <br>
                          in .Message1.Test
                        <br>
                        ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.
                        <br>
                          in .Message1.Test2
                        <br>
                        <br>
                          in .Message1.DE Director
                        <br>
                        Because:
                        <br>
                        The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.
                        <br>
                          in .Message1.Test
                        <br>
                        	at ptolemy.actor.Director.wrapup(Director.java:1736)
                        <br>
                        	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1527)
                        <br>
                        	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2755)
                        <br>
                        	at ptolemy.actor.Manager.wrapup(Manager.java:1530)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:407)
                        <br>
                        	at ptolemy.actor.Manager.run(Manager.java:1263)
                        <br>
                        	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.
                        <br>
                          in .Message1.Test
                        <br>
                        	at ptolemy.actor.lib.NonStrictTest.wrapup(NonStrictTest.java:394)
                        <br>
                        	at ptolemy.actor.Director.wrapup(Director.java:1722)
                        <br>
                    </code></td><td>21.218</td>
            </tr>
            <tr valign="top" class="Error">
                <td><a href="ptolemy/actor/lib/test/junit/79_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[149] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/test/auto/ExecutionTimeSDF.xml (RunModel)"></a><a href="ptolemy/actor/lib/test/junit/79_JUnitTclTest.html#[149] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/test/auto/ExecutionTimeSDF.xml (RunModel)">[149] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/test/auto/ExecutionTimeSDF.xml (RunModel)</a></td><td>Error</td><td>N/A
                    <br>
                    <br>
                    <code>java.lang.reflect.InvocationTargetException
                        <br>
                        	at jdk.internal.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        <br>
                        	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                        <br>
                        	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:193)
                        <br>
                        	at jdk.internal.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
                        <br>
                        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        <br>
                        	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
                        <br>
                        Caused by: ptolemy.kernel.util.IllegalActionException: Test fails in iteration 0.
                        <br>
                        Value was: 6007L. Should have been: 6000L
                        <br>
                          in .ExecutionTimeSDF.NonStrictTest
                        <br>
                        	at ptolemy.actor.lib.NonStrictTest.postfire(NonStrictTest.java:328)
                        <br>
                        	at ptolemy.actor.AtomicActor.iterate(AtomicActor.java:518)
                        <br>
                        	at ptolemy.actor.sched.StaticSchedulingDirector.fire(StaticSchedulingDirector.java:216)
                        <br>
                        	at ptolemy.domains.sdf.kernel.SDFDirector.fire(SDFDirector.java:500)
                        <br>
                        	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)
                        <br>
                        	at ptolemy.actor.Manager.iterate(Manager.java:851)
                        <br>
                        	at ptolemy.actor.Manager.execute(Manager.java:369)
                        <br>
                        	at ptolemy.actor.Manager.run(Manager.java:1263)
                        <br>
                        	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1933)
                        <br>
                    </code></td><td>6.069</td>
            </tr>
        </table>
    </body>
</html>
